services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  mongo:
    container_name: mongo_for_redis
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongo_for_redis
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data: